"""Write tables/olmologic/full_samestack.tex: all three 7B models evaluated by us with OLMES (same stack)."""
import json
P='./rebuttal/olmologic_eval_scratch/olmes_rows.json'
OUT='paper/tables/olmologic/full_samestack.tex'
r=json.load(open(P)); V={m:{k:v[0] for k,v in r[m]['rows'].items()} for m in r}
TH,LG,O31='Olmo-3-7B-Think','OlmoLogic-7B-Think','Olmo-3.1-7B-Think'
G=[('Logical Reasoning',[('SLR-Bench','SLR-Bench'),('LogiGLUE (22)','LogiGLUE'),('Abduction','Abduction'),('ADV','LogiGLUE adv'),('ANLI','LogiGLUE anli'),('bAbI','bAbI'),('BirdElectricity','LogiGLUE birdelectricity'),('CLUTTR','CLUTTR'),('FOLIO','LogiGLUE folio'),('LogiQA 2.0','LogiGLUE logiqa_2_0'),('NatLang Reasoning','LogiGLUE natlang'),('ProntoQA','LogiGLUE prontoqa'),('ReClor','LogiGLUE reclor'),('RuleBERT','RuleBERT'),('ZebraLogic','ZebraLogic'),('KOR-Bench','KOR-Bench')]),
   ('Reasoning \\& Math',[('BBH (27)','BBH (27)'),('AGI Eval English','AGI Eval English'),('MATH','MATH'),('GSM8K','GSM8K'),('AIME 2024','AIME 2024'),('AIME 2025','AIME 2025')]),
   ('Knowledge \\& QA',[('MMLU','MMLU'),('GPQA','GPQA'),('ARC Challenge','ARC Challenge'),('PopQA','PopQA')]),
   ('Coding',[('HumanEvalPlus','HumanEvalPlus'),('MBPP+','MBPP+'),('LiveCodeBench v3','LiveCodeBench v3')]),
   ('Instruction Following \\& Chat',[('IFEval','IFEval'),('IFBench','IFBench'),('AlpacaEval 2 LC','AlpacaEval 2 LC')]),
   ('Safety',[('Safety Avg (11)','Safety Avg')])]
def f(x): return f"{x:.1f}"
def d(x):
    s=f"{x:+.1f}".replace('+','') if x>=0 else f"{x:.1f}"
    return "\\deltaval{"+s+"}"
L=[]
L.append("% ICLR-final: same-stack OLMES table generated by rebuttal/olmologic_figs/make_samestack_table.py; replaces tables/olmologic/full.tex (mixed AI2-reported / OLMES baseline).")
L.append("\\begin{table*}[t]\n\\centering\n\\footnotesize\n\\setlength\\tabcolsep{4pt}\n\\renewcommand{\\arraystretch}{0.95}")
L.append("\\rebuttal{\\begin{tabular}{@{}l r r r@{}}\n\\toprule")
L.append("& \\textbf{\\texttt{Olmo-3 7B Think}} & \\textbf{\\texttt{Olmo-3 7B Logic}} (ours) & \\textbf{\\texttt{Olmo-3.1 7B Think}} (ours) \\\\\n\\midrule")
for g,items in G:
    L.append(f"\\rowcolor{{midgrey}} \\textbf{{{g}}} & & & \\\\")
    for lab,key in items:
        a,b,c=V[TH][key],V[LG][key],V[O31][key]
        best=max(a,b,c)
        def cell(x,extra=''):
            s=f(x); s=("\\textbf{"+s+"}") if abs(x-best)<0.05 else s
            return s+extra
        L.append(f"\\rowcolor{{lightgrey}} \\metric{{{lab}}} & {cell(a)} & {cell(b,' '+d(b-a))} & {cell(c,' '+d(c-a))} \\\\")
    L.append("\\midrule")
L[-1]="\\bottomrule"
L.append("\\end{tabular}}")
L.append("\\caption{\\rebuttal{\\textbf{Downstream evaluation of \\symbols{Olmo-3-7B-Logic} on the Olmo-3 post-training suite, same evaluation stack for all three models.} \\symbols{Olmo-3-7B-Logic} continues RLVR from \\symbols{Olmo-3-7B-Think-DPO} on the Olmo-3 RLVR data plus \\benchmark{} with the isomorphic verifier (3{,}350 steps); \\symbols{Olmo-3.1-7B-Think} is the same continuation without \\benchmark{}. All numbers are our own OLMES evaluations with identical task configurations (\\texttt{olmo3:adapt}, 32k tokens, temperature 0.6), including the \\symbols{Olmo-3-7B-Think} baseline, which reproduces the officially reported values within about one point. Deltas are relative to \\symbols{Olmo-3-7B-Think}; bold marks the best of the three. OMEGA is omitted because its subtask coverage is incomplete for two of the models.}}")
L.append("\\label{tab:post-train-eval-overview}\n\\end{table*}")
open(OUT,'w').write('\n'.join(L)+'\n'); print('wrote',OUT, sum(len(i) for _,i in G),'rows')
